server:
  port: 9001
  context-path: /app
  session:
    cookie:
      name: zdesk_app_token
debug: true
spring:
  aop:
    proxy-target-class: true
security:
  basic:
    enabled: false
zdesk:
  client:
    client-id: zdesk
    client-secret: zdesksecret
    access-token-uri: http://localhost:8080/oauth/token
    user-authorization-uri: http://localhost:8080/oauth/authorize
    grant-type: authorization_code
    pre-established-redirect-uri: http://localhost:9001/app/
    registered-redirect-uri: http://localhost:9001/app/
    use-current-uri: false
  resource:
    userInfoUri: http://localhost:8080/user
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    user:
      path: /user/**
      url: http://localhost:8080/me
logging:
  level:
    org.springframework.security: DEBUG