server:
  port: 9001
  context-path: /app
debug: true
spring:
  aop:
    proxy-target-class: true
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: zdesk
      client-secret: zdesksecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      grant-type: implicit
    resource:
      jwt:
        keyUri: http://localhost:8080/oauth/token_key
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    user:
      path: /user/**
      url: http://localhost:8080/me
logging:
  level:
    org.springframework.security: DEBUG