server:
  port: 9000
  context-path: /resource
  
security:
  oauth2:
    resource:
      jwt:
        keyUri: http://localhost:8080/oauth/token_key

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG