server:
  port: 9999
logging:
  level:
    org.springframework.security: DEBUG

spring:
  aop:
    proxy-target-class: true

security:
  oauth2:
    resource:
      jwt:
        keyUri: http://localhost:8080/auth/oauth/token_key


resourceServerClient:
  accessTokenUri: http://localhost:8080/auth/oauth/token
  userInfoUri: http://localhost:8080/auth/user
  pre-established-redirect-uri: http://localhost:9999/oauth
  use-current-uri: false
  clientId: zdesk
  clientSecret: zdesksecret
  
  
facebook:
  client:
    clientId: 692899840881825
    clientSecret: 61ac73198af844fed4b5a19dec8bfe1e
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    scope: email
    display: popup
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,picture,email